### ISSUE TITLE
[FR]: 3-way toggle

### ISSUE THREAD

**Issue by ksdavidc** [Mara-Li/obsidian-edit-shortcut#2] opened 2024-10-10 00:58 UTC
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

sort of. It seems to me that having 2 buttons for 3 modes doesn't quite make sense.

### What solution do you want to see ?

 Do you think you could implement a 3 way toggle?? Either as a button, or as a hotkey?

### OS

MacOS

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 23.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 50
	Plugins enabled: 46
		1: File Tree Alternative v2.6.0
		2: Image Context Menus v1.9.1
		3: Doubleshift v2.2.1
		4: Calendar v1.5.10
		5: Auto Embed v1.2.2
		6: PDF++ v0.40.11
		7: BRAT v1.0.3
		8: MySnippets v1.2.3
		9: UNITADE.md v2.4.0
		10: Advanced URI v1.44.1
		11: Linter v1.26.0
		12: Plugin Update Tracker v1.5.2
		13: Tasks v7.11.0
		14: Task list v1.0.1
		15: Better Command Palette v0.17.1
		16: Task Marker v0.5.1
		17: Create Task v1.4.2
		18: Blockier v1.1.0
		19: Regex Find/Replace v1.2.0
		20: Create List of Notes v1.0.6
		21: Waypoint v2.1.0
		22: Annotator v0.2.11
		23: Dataview v0.5.67
		24: Settings Search v1.3.10
		25: Virtual Linker / Glossary v1.5.0
		26: Projects v1.17.4
		27: Link Converter v0.1.6
		28: Note Refactor v1.8.2
		29: Text Transporter v1.0.11
		30: Tag Project v0.9.0
		31: Style Settings v1.0.9
		32: Templater v2.8.0
		33: Folder Note Core v1.3.5
		34: AidenLx's Folder Note - folderv component v1.0.0
		35: AidenLx's Folder Note v0.16.5
		36: Icon Shortcodes v0.9.7
		37: Datepicker v0.3.23
		38: Natural Language Dates v0.6.2
		39: Control Characters v0.3.0
		40: Time Ruler v2.5.1
		41: Notice logger v0.1.1
		42: Better PDF 2 v2.0.3
		43: Settings Management v1.0.5
		44: Plugins Annotations v1.7.2
		45: Enhance YouTube Links v1.0.8
		46: Edit mode switch v0.0.3

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Plugin version

1.3.10

**Comment by Mara-Li** [comment] 2024-10-10 03:26
What do you mean by 3 way toggle?

**Comment by ksdavidc** [comment] 2024-10-10 04:45
Right now your button has 2  states for 2 views, and cycles through these. 
The button I suggest has 3 states corresponding to 3 views/modes: (source, preview, reading) 
Pressing the button cycles through the states in order.

**Comment by Mara-Li** [comment] 2024-10-10 17:36
It's a little out of the scope of the plugin, as you have already a shortcuts to switch between edit/read view. You can use Commander to add the button on the file header, if you want.

**Comment by merlinuwe** [comment] 2024-11-21 21:04
Thanks for your plugin. 

I would like to have one 3-way-toggle (or shortcut-enhancement ) for windows. ;-)

read -> source-view -> live-preview -> read ...

Everytime one presses <Strg-e>, it switches the note view to the next one.

**Comment by Mara-Li** [comment] 2024-11-22 05:54
In fact after usage of my plugin, this option could be useful

**Comment by Mara-Li** [comment] 2024-11-22 22:58
Okay, I worked a little time on it, and I have a problem. Actually, it's not possible to switch between the three.
When you go in reading mode, the toggle to switch between LP & Source is disabled, and I need to toggle it again. But, if you was previously in source, it will open the editor in source mode. Meaning I need to switch **again**. Actually, there is no toggle to force the editor to open in LP (or source, in another order).

Consequence ? It “blinks” when switching to LP. 

If you want, you can try the branch linked to this suggestion: [three-mode-toggle.zip](https://github.com/user-attachments/files/17877254/three-mode-toggle.zip)

I will probably add a warning about it in the settings if too much disruptive.

**Comment by ksdavidc** [comment] 2024-11-23 08:06
not quite working yet for me..LP shows up first time, but disappears after that.

https://github.com/user-attachments/assets/7e5e5647-a53a-4d08-bc6f-62b0e2290c89

**Comment by Mara-Li** [comment] 2024-11-23 19:44
You need to reload the page to make it works after the first enable

**Comment by ksdavidc** [comment] 2024-11-23 21:58
It took a few tries, but seems to be working. No "blinking" observed as yet. I like it, thank you.

**Comment by merlinuwe** [comment] 2024-11-24 18:49
I'm on windows 10 with obsidian 1.7.7 and tested https://github.com/user-attachments/files/17877254/three-mode-toggle.zip



With these settings I always see a flickering, but no change.

![image](https://github.com/user-attachments/assets/3afab7e8-8fe7-4292-89ca-a24be0469b0e)

I only see this page, not changing to an other view:

![image](https://github.com/user-attachments/assets/26c8e9b0-b726-4551-a905-5bb698cd4d3a)

What settings should I use to toggle between read -> source-view -> live-preview

**Comment by Mara-Li** [comment] 2024-11-24 20:59
Will try tomorrow!

**Comment by Mara-Li** [comment] 2024-11-25 07:52
Should work, now:
[obsidian-edit-shortcut.zip](https://github.com/user-attachments/files/17899311/obsidian-edit-shortcut.zip)

**Comment by merlinuwe** [comment] 2024-11-25 09:25
Thank you very much, it does work. Here are the steps to reproduce on windows 10 with Obsidian 1.7.7:

Installing your code and then restarting Obsidian seems to be necessary.

1. When I open the note, it starts in live-preview mode. It shows this icon 
![image](https://github.com/user-attachments/assets/37cfcd9d-254f-4b59-a678-45bbd572c034)
 with the hover text "Live Preview".

2. One time pressing on the icon 
![image](https://github.com/user-attachments/assets/afbb9a0e-009b-4fb4-9f50-f3377ef4cd7a)
 changes to source mode. It shows this icon 
![image](https://github.com/user-attachments/assets/8be2356c-3fd8-436c-ad1c-a2b56bb93ac9)
 with the hover text "Source mode".

3. One time pressing on the icon 
![image](https://github.com/user-attachments/assets/5c0f004f-3cf1-4415-951e-910b1aa34c00)
 changes to reading view. It shows the icon 
![image](https://github.com/user-attachments/assets/12835667-e0d2-4a9f-9e6f-9f5e7be8f181)
 with the hover text "Reading view".

4. One time pressing on the icon 
![image](https://github.com/user-attachments/assets/e4abdfd5-5f2b-485b-8a6d-d1b72ee3b9d9) 
changes to live preview. It shows the icon 
![image](https://github.com/user-attachments/assets/77a3aec2-272d-4026-a849-0067e0f56adb)
with the hover text Live Preview.

Here are my settings:

![image](https://github.com/user-attachments/assets/6e5e899d-f065-438c-9451-88b81e7189bd)
 
![image](https://github.com/user-attachments/assets/c745f1b6-dc81-444a-912c-f8323028a207)

Again, thank you very much for your great work which is very useful!

**Comment by Mara-Li** [comment] 2024-11-25 10:50
I don't see the problem?
Sorry

**Comment by merlinuwe** [comment] 2024-11-25 11:10
There is no problem.  I documented, that it works. ;-)

But while you're asking: Is it possible to assign a key combination?

**Comment by Mara-Li** [comment] 2024-11-25 11:32
No, but I can add a command to toggle the command! Will do it asap ;)

**Comment by Mara-Li** [comment] 2024-11-25 12:04
[obsidian-edit-shortcut.zip](https://github.com/user-attachments/files/17902601/obsidian-edit-shortcut.zip)

**Comment by merlinuwe** [comment] 2024-11-26 19:56
Thank you sooo much! I already have assigned the shortcut `<Ctrl-Alt-e>` and it works perfect. ;-)

![image](https://github.com/user-attachments/assets/edd4d421-901c-4809-b35e-82018284c104)

**Comment by merlinuwe** [comment] 2024-12-07 18:16
Hi, 

I found a bug.  I use Commander plugin to call your plugin (with the first icon in the pink frame).

![image](https://github.com/user-attachments/assets/f76814bb-e68b-4cfc-9521-fb834a758257)

When I click through the following buttons (the note is visible in source mode) in Obsidians left pane

![image](https://github.com/user-attachments/assets/f1772385-28da-4d04-ae65-4ae77414da54)

these buttons get more and more, with every click:

![image](https://github.com/user-attachments/assets/c2aec8aa-d393-4d7e-a88f-e78069415699)

Depending on the mode, the icons change:

Live preview:

![image](https://github.com/user-attachments/assets/7efbff2b-fbb6-4ee9-a6e5-0e8e83ecf5c4)

Reading:

![image](https://github.com/user-attachments/assets/f82c92f7-77e9-41d2-aa0d-08b3987a81e0)

Switching between the 3 modes resets the multiple shown icons.

If I switch your plugin off, the issue disappears.

(Windows 10, with Obsidian 1.7.7 and your latest in this threat provided plugin.)

**Comment by merlinuwe** [comment] 2024-12-16 15:45
I found the problem:

![image](https://github.com/user-attachments/assets/25bb80df-677e-4832-ae01-f54d70edfffc)

The Commander plugin had a macro defined, who did this.

You can close this issue. Thanks a LOT for realizing this useful plugin!

**Closed as completed** 2024-12-17 06:37 UTC
Labels: enhancement
